config/routes.rb
Bees::Application.routes.draw do

  
  

  get "comments/create"

  get "account", to: "account#index"
  get "account/subscription", to: "account#subscription"
  get "account/order", to: "account#order"

  resources :subscriptions
  post "subscriptions/new"
  get "confirm_subscription", to: "gocardless#confirm_subscription"
  get 'cancel_subscription', to: 'subscriptions#cancel_subscription'
  get 'confirm_cancel_subscription', to: 'gocardless#confirm_cancel_subscription'

  get "join", to: 'join#index' 

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  resources :sessions
  resources :users
  
  match 'articles/category', to: 'articles#category'
  match 'articles/all', to: 'articles#all'
	match 'articles/:permalink', to: 'articles#show'
	get 'blog', to: 'articles#index'
	resources :article_categories
	resources :articles
	resources :comments
  
  get 'craft_boxes', to: 'pages#craft_boxes'
  get 'about_us', to: 'pages#about_us'
	get 'terms', to: 'pages#terms'
	get 'faq', to: 'pages#faq'
  get 'privacy', to: 'pages#privacy'
  get 'contact', to: 'pages#contact'
  get 'newsletter', to: 'pages#newsletter'
  get 'reset_password', to: 'sessions#reset_password'
  get 'change_password', to: 'account#change_password'
  post 'send_contact_form', to: 'pages#send_contact_form'
  post 'newsletter_signup', to: 'pages#newsletter_signup'
  post 'send_new_password', to: 'sessions#send_new_password'
  post 'send_change_password', to: 'account#send_change_password'

  resources :shop_cart_items
  
  get 'shop', to: 'shop#index'
  match 'shop/category', to: 'shop#category'
  get 'shop/product_details'
  get 'shop/basket'
  get 'shop/checkout'
  post 'shop/create_order'
  get 'shop/empty_basket'
  post 'shop_cart_items/update_items'
  get 'confirm_shop_order', to: 'gocardless#confirm_shop_order'

  get 'manager', to: 'manager#index'
  get 'manager/subscription_details', to: 'manager#subscription_details'
  get 'manager/pack_sheets', to: 'manager#pack_sheets'
  get 'manager/orders', to: 'manager#orders'
  get 'manager/order_details', to: 'manager#order_details'
  post 'manager/update_order_status', to: 'manager#update_order_status'
  get 'manager/sort_orders', to: 'manager#sort_orders'

  get 'manager/month_end', to: 'manager#month_end'
  post 'manager/process_month_end', to: 'manager#process_month_end'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#index'

end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_filter :authenticate_admin_user!
  before_filter :get_order_statuses

  def index
  	@subscriptions = Subscription.where("status = ?", "Active").order("created_at DESC")
    @cancelled = Subscription.where("status = ?", "Cancelled").order("created_at DESC")
    @comments = Comment.where("status = ?", "pending").count
    @m_end = MonthlySale.find(:all, :conditions => ["created_at between ? and ?",
             Date.today.beginning_of_month, Date.today.end_of_month])
    @orders = ShopOrder.all
  end

  def subscription_details
  	@subscription = Subscription.find(params[:id])
  end

  def pack_sheets
  	@subscriptions = Subscription.where("status = ?", "Active").order("created_at DESC")
  	render :layout => nil
  end

  def orders
    @orders = ShopOrder.all
    
  end

  def sort_orders
    @orders = ShopOrder.status_sort(params[:status])
  end

  def order_details
    @order = ShopOrder.find(params[:id])
  end

  def update_order_status
    @order = ShopOrder.find(params[:order_id])
    @order.update_attributes(:order_status_id => params[:order_status])

    # send email to customer to tell them order status has been updated

    redirect_to manager_order_details_path(:id => params[:order_id]), notice: "Order status has been updated"
  end

  def month_end
    @subs = Subscription.where("status = ?", "Active")
  end

  def process_month_end
    # Get status for each subscription, from GoCardless, and update
    subs = Subscription.where("status = ?", "Active")
    count = 0
    subs.each do |sub|
      subscription = GoCardless.client.subscription(sub.resource_id)
      if subscription.status == "cancelled"
        sub.update_attributes(:status => "Cancelled")
      else
      # Create sales records for the month
      box_no = ((Date.today.year*12+Date.today.month) - (sub.first_delivery.year*12+sub.first_delivery.month) + 1)
      next_box = Box.find_by_box_number(box_no)
      sale = MonthlySale.new(subscription_id: sub.id, box_id: next_box.id)
      count = count + 1
      end
    end
    redirect_to manager_month_end_path, notice: "Job has been processed #{count} times"
  end

  def get_order_statuses
    @statuses = OrderStatus.all
  end

end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/views/manager/_status_menu.html.erb
<p>
	<%= link_to "All", manager_orders_path %> | 
	<% @statuses.each do |status| %>
		<%= link_to status.name, manager_sort_orders_path(:status => status.name) %> | 
	<% end %>
	</p>

app/views/manager/index.html.erb
<div class="row mbottom30">
	<h4>Admin Area</h4>

	<p>There are <%= @comments %> comments waiting to be checked.</p>
	

</div>

<div class="row mbottom30">
	<div class="panel">
		<h5>Subscriptions</h5>
		<% if @subscriptions.empty? %>
			<p>There are no subscriptions yet :(</p>
		<% else %>
		<table width="99%">
			<thead>
				<tr>
					<th>Item</th>
					<th>Price</th>
					<th>Start Date</th>
					<th>Status</th>
					<th>Ordered</th>
				</tr>
			</thead>
			<tbody>
				<% @subscriptions.each do |sub| %>
				<tr>
					<td><%= link_to sub.subscription_items.first.product.name, manager_subscription_details_path(id: sub.id) %></td>
					<td><%= number_to_currency(sub.subscription_items.first.price) %></td>
					<td><%= sub.first_delivery.strftime('%d/%m/%Y')  %></td>
					<td><%= sub.status %></td>
					<td><%= sub.created_at.strftime('%d/%m/%Y') %></td>
				</tr>
				<% end %>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				<% @cancelled.each do |cancel| %>
					<tr class="cancelled">
						<td><%= cancel.subscription_items.first.product.name %></td>
						<td><%= number_to_currency(cancel.subscription_items.first.price) %></td>
						<td><%= cancel.first_delivery.strftime('%d/%m/%Y')  %></td>
						<td><%= cancel.status %></td>
						<td><%= cancel.created_at.strftime('%d/%m/%Y') %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		
		<% end %>

		<h5>Orders</h5>
		<% if @orders.empty? %>
			<p>There are no shop orders.</p>
		<% else %>
			<p>There <%= pluralize_without_count(@orders.count, "is") %> <%= pluralize(@orders.count, "order") %></p>
			<% @orders.each do |ord| %>
				<%= ord.order_total %> - <%= ord.order_status.name %>
			<% end %>
		<% end %>

	</div>
	<% if @m_end.empty? %>
		<p><%= link_to "Month End Job", manager_month_end_path, class: "button nice radius small" %></p>
	<% else %>
		<p>Month end job has already been run</p>
	<% end %>
</div>

app/views/manager/month_end.html.erb
<div class="row mbottom30">
	<h4>Process Month End Jobs</h4>

	<p>This will check all subscriptions to see if they are still active. It will then create a sale record for each active subscription.</p>

	<%= button_to "Process Monthly Jobs", manager_process_month_end_path %>

</div>

app/views/manager/order_details.html.erb
<div class="row mbottom30">
	<h4>Admin Area - Order Details</h4>
	<p><%= link_to "Back to all orders", manager_orders_path %></p>
</div>

<div class="row mbottom30">
	
		<div class="eight columns">
				<div class="row mbottom30">
					<table class="nice" width="100%">
						<thead>
							<tr>
								<th>Item</th>
								<th>Item Price</th>
								<th>Quantity</th>
								<th>Total</th>
							</tr>
						</thead>
						<tbody>
							<% @order.shop_order_items.each do |item| %>
								<tr>
									<td><%= item.shop_product.name %></td>
									<td><%= number_to_currency(item.shop_product.sell) %></td>
									<td><%= item.quantity %></td>
									<td><%= number_to_currency(item.total_price) %></td>
								</tr>
							<% end %>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
							<% subtotal = @order.total_order_price
							 	weight = @order.total_order_weight
								if subtotal > 50
									delivery = 0.00
								else
							 		delivery = @order.delivery_charge(weight)
							 	end %>
								<tr>
									<td></td>
									<td></td>
									<td>Subtotal:</td>
									<td><%= number_to_currency(subtotal) %></td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td>Delivery:</td>
									<td><%= number_to_currency(delivery) %></td>
								</tr>
								<tr>
									<td></td>
									<td></td>
									<td><strong>Total:</strong></td>
									<td><strong><%= number_to_currency(subtotal + delivery) %></strong></td>
								</tr>
						</tbody>
					</table>
				</div>
			
		</div>
		
		<div class="four columns">
			<div class="panel">
				<h5>Order Reference</h5>
				<p><%= @order.resource_id %> - <%= @order.id %></p>

				<h5>Status</h5>
				<p><%= @order.order_status.name %></p>
				<p>
					<%= form_tag manager_update_order_status_path do %>
						<%= select_tag 'order_status', options_from_collection_for_select(OrderStatus.all, 'id', 'name', @order.order_status.id) %>
						<%= hidden_field_tag 'order_id', @order.id %>
						<%= submit_tag "Change", class: "button small radius nice" %>
					<% end %>
					</p>

				<h5>Order Date</h5>
				<p><%= @order.created_at.strftime('%d/%m/%Y') %></p>

				<h5>Delivery Address</h5>
				<p><%= @order.name %></p>
				<p><%= simple_format(@order.address) %></p>
			</div>
		</div>
		
	
</div>

app/views/manager/orders.html.erb
<div class="row mbottom30">
	<h4>Admin Area - Orders</h4>
	<%= render 'manager/status_menu' %>
</div>

<div class="row mbottom30">
	<div class="panel">
		<h5>Orders</h5>
		<% if @orders.empty? %>
			<p>There are no orders yet :(</p>
		<% else %>
		<table width="99%">
			<thead>
				<tr>
					<th>ID</th>
					<th>Date</th>
					<th>Status</th>
					<th>Name</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% @orders.each do |ord| %>
				<tr>
					<td><%= link_to ord.id, manager_order_details_path(:id => ord.id) %></td>
					<td><%= ord.created_at.strftime('%d/%m/%Y') %></td>
					<td><%= ord.order_status.name %></td>
					<td><%= ord.name  %></td>
					<td><%= number_to_currency(ord.order_total) %></td>
				</tr>
				<% end %>
				
			</tbody>
		</table>
		
		<% end %>

	</div>
	
</div>

app/views/manager/pack_sheets.html.erb

<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Pontano+Sans' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  	<%= csrf_meta_tags %>
  	<style type="text/css">
  		.page-break  { display: block; page-break-after: always; }
  		tr { text-align: left; }
  		td { border-bottom: 1px solid #ccc; }
  	</style>
</head>

<body>
	<% if @subscriptions.empty? %>
		<div id="a4page">
			<p>There are no subscriptions to delivery. You're obviously not working hard enough!</p>
		</div>
	<% else %>
	
	<% @subscriptions.each do |sub| %>
	<div id="a4page">
		<h1>PICK SHEET</h1>
		<h3>Delivery Details</h3>
		<p><%= sub.street %><br />
			<%= sub.town %><br />
			<%= sub.county %><br />
			<%= sub.postcode %>
		</p>

		<p><%= sub.subscription_items.first.recipient1 %> - 
		<%= sub.subscription_items.first.age1 %> - 
		<%= sub.subscription_items.first.gender1 %></p>
		<p><%= sub.subscription_items.first.recipient2 %> - 
		<%= sub.subscription_items.first.age2 %> - 
		<%= sub.subscription_items.first.gender2 %></p>

		<% if !sub.gift_message.blank? %>
			<h4>Gift Message</h4>
			<p><%= sub.gift_message %></p>
		<% else %>
			<p>No Gift Message!</p>
		<% end %>

		<table class="nice" width="99%">
			<thead>
				<tr>
					<th>Item</th>
					<th>Box Number</th>
					<th>Box Name</th>
				</tr>
			</thead>
			<tbody>
				<% sub.subscription_items.each do |item| %>
					<% box_no = ((Date.today.year*12+Date.today.month) - (sub.first_delivery.year*12+sub.first_delivery.month) + 1) %>
					<% next_box = Box.find_by_box_number(box_no) %>
					<tr>
						<td><%= item.product.name %></td>
						<td><strong><%= box_no %></strong></td>
						<td><strong><%= next_box.name %></strong></td>
					</tr>
				<% end %>
			</tbody>	
		</table>

		<h4>Box Items</h4>

		<table class="nice" width="99%">
			<thead>
				<tr>
					<th>Item</th>
					<th>Quantity</th>
					<th>Picked</th>
				</tr>
			</thead>
			<tbody>
				<% box_no = ((Date.today.year*12+Date.today.month) - (sub.first_delivery.year*12+sub.first_delivery.month) + 1) %>
				<% next_box = Box.find_by_box_number(box_no) %>
				<% next_box.box_contents.each do |con| %>
					<tr>
						<td><%= con.stock_item.name %></td>
						<td><strong><%= con.quantity %></strong></td>
						<td></td>
					</tr>
				<% end %>
			</tbody>	
		</table>

		<p>Picked By: </p>

	</div>
	<div class="page-break"></div>
	<% end %>
	<% end %>
</body>

</html>

app/views/manager/sort_orders.html.erb
<div class="row mbottom30">
	<h4>Admin Area - Orders</h4>
	<%= render 'manager/status_menu' %>
</div>

<div class="row mbottom30">
	<div class="panel">
		<h5>Orders</h5>
		<% if @orders.empty? %>
			<p>There are no orders at this status</p>
		<% else %>
		<table width="99%">
			<thead>
				<tr>
					<th>ID</th>
					<th>Date</th>
					<th>Status</th>
					<th>Name</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% @orders.each do |ord| %>
				<tr>
					<td><%= link_to ord.id, manager_order_details_path(:id => ord.id) %></td>
					<td><%= ord.created_at.strftime('%d/%m/%Y') %></td>
					<td><%= ord.order_status.name %></td>
					<td><%= ord.name  %></td>
					<td><%= number_to_currency(ord.order_total) %></td>
				</tr>
				<% end %>
				
			</tbody>
		</table>
		
		<% end %>

	</div>
	
</div>

app/views/manager/subscription_details.html.erb
<div class="row mbottom30">
	<h4>Subscription Details</h4>
	<p><%= link_to "<< back to subscriptions", manager_path %></p>
</div>

<div class="row mbottom30">
	<div class="six columns">
		<div class="panel">
			<div class="twelve columns"
				<p><%= @subscription.user.email %><br />
					<%= @subscription.street %><br />
					<%= @subscription.town %><br />
					<%= @subscription.county %><br />
					<%= @subscription.postcode %>
				</p>
			</div>
			<table class="nice" width="99%">
				<thead>
					<tr>
						<th>Name</th>
						<th>Age</th>
						<th>Gender</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @subscription.subscription_items.first.recipient1 %></td>
						<td><%= @subscription.subscription_items.first.age1 %></td>
						<td><%= @subscription.subscription_items.first.gender1 %></td>
					</tr>
					<tr>
						<td><%= @subscription.subscription_items.first.recipient2 %></td>
						<td><%= @subscription.subscription_items.first.age2 %></td>
						<td><%= @subscription.subscription_items.first.gender2 %></td>
					</tr>
				</tbody>
			</table>
			</div>
	</div>
	<div class="six columns">
		<div class="panel">
			<p>Status: <%= @subscription.status %><br />
				First Del. : <%= @subscription.first_delivery.strftime('%d/%m/%Y') %><br />
				GC Sub ID: <%= @subscription.resource_id %>			
			</p>
			<p>Box Number: <%= ((Date.today.year*12+Date.today.month) - (@subscription.first_delivery.year*12+@subscription.first_delivery.month) + 1) %></p>
		</div>
	</div>
</div>
<% if !@subscription.gift_message.blank? %>
<div class="row mbottom30">
	<div class="twelve columns">
		<div class="panel">
			<h4>Gift Message</h4>
			<p><%= @subscription.gift_message %></p>
		</div>
	</div>
</div>
<% end %>

<div class="row mbottom30">
	<div class="twelve columns">
		<div class="panel">
			<h3>Item</h3>
			<table class="nice" width="99%">
				<thead>
					<tr>
					<th>Item</th>
					<th>Price</th>
				</tr>
				</thead>
				<tbody>
					<% @subscription.subscription_items.each do |item| %>
					<tr>
						<td><%= item.product.name %></td>
						<td><%= number_to_currency(item.price) %></td>
					</tr>
					<% end %>
				</tbody>	
			</table>
		</div>
	</div>
</div>