config/routes.rb
Bees::Application.routes.draw do

  
  

  get "comments/create"

  get "account", to: "account#index"
  get "account/subscription", to: "account#subscription"
  get "account/order", to: "account#order"

  resources :subscriptions
  post "subscriptions/new"
  get "confirm_subscription", to: "gocardless#confirm_subscription"
  get 'cancel_subscription', to: 'subscriptions#cancel_subscription'
  get 'confirm_cancel_subscription', to: 'gocardless#confirm_cancel_subscription'

  get "join", to: 'join#index' 

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  resources :sessions
  resources :users
  
  match 'articles/category', to: 'articles#category'
  match 'articles/all', to: 'articles#all'
	match 'articles/:permalink', to: 'articles#show'
	get 'blog', to: 'articles#index'
	resources :article_categories
	resources :articles
	resources :comments
  
  get 'craft_boxes', to: 'pages#craft_boxes'
  get 'about_us', to: 'pages#about_us'
	get 'terms', to: 'pages#terms'
	get 'faq', to: 'pages#faq'
  get 'privacy', to: 'pages#privacy'
  get 'contact', to: 'pages#contact'
  get 'newsletter', to: 'pages#newsletter'
  get 'reset_password', to: 'sessions#reset_password'
  get 'change_password', to: 'account#change_password'
  post 'send_contact_form', to: 'pages#send_contact_form'
  post 'newsletter_signup', to: 'pages#newsletter_signup'
  post 'send_new_password', to: 'sessions#send_new_password'
  post 'send_change_password', to: 'account#send_change_password'

  resources :shop_cart_items
  
  get 'shop', to: 'shop#index'
  match 'shop/category', to: 'shop#category'
  get 'shop/product_details'
  get 'shop/basket'
  get 'shop/checkout'
  post 'shop/create_order'
  get 'shop/empty_basket'
  post 'shop_cart_items/update_items'
  get 'confirm_shop_order', to: 'gocardless#confirm_shop_order'

  get 'manager', to: 'manager#index'
  get 'manager/subscription_details', to: 'manager#subscription_details'
  get 'manager/pack_sheets', to: 'manager#pack_sheets'
  get 'manager/orders', to: 'manager#orders'
  get 'manager/order_details', to: 'manager#order_details'
  post 'manager/update_order_status', to: 'manager#update_order_status'
  get 'manager/sort_orders', to: 'manager#sort_orders'

  get 'manager/month_end', to: 'manager#month_end'
  post 'manager/process_month_end', to: 'manager#process_month_end'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#index'

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  
  before_filter :get_shop_cats, :get_cart_items

  def index
    @page_title = "Craft Shop"
    @products = ShopProduct.where("is_active = ?", true).order("RANDOM()")
  end

  def category
  	@categ = ShopProductCategory.find_by_name(params[:name])
  	if @categ.nil?
  		redirect_to shop_path
  	else
  	  @page_title = @categ.name
  		@products = ShopProduct.where("shop_product_category_id = ? AND is_active = ?", @categ.id, true).order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  	end
  end

  def product_details
	@item = ShopProduct.find(params[:id])
	@page_title = @item.name
	@others = ShopProduct.where("shop_product_category_id = ? AND id != ?", @item.shop_product_category_id, @item.id).order("RANDOM()").limit(4)
  end

  def basket
    @shop_cart = current_shop_cart
  end
  
  def checkout
    @shop_cart = current_shop_cart
  end
  
  def empty_basket
    cart = ShopCart.find(session[:shop_cart_id])
    cart.destroy
    redirect_to shop_path, notice: "Your basket has been emptied"
  end

  def get_shop_cats
	  @categories = ShopProductCategory.all
  end
  
  def get_cart_items
    @cart_items = ShopCartItem.where("shop_cart_id= ?", session[:shop_cart_id])
  end
  
  def create_order
    if params[:name].empty? || params[:address].empty?
      redirect_to shop_checkout_path, alert: "Please fill in all required fields"
    else
      @shop_cart = current_shop_cart
      
      # create user if not exists
      if !current_user
        # see if email exists if not logged in
        @user = User.find_by_email(params[:email])
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
        else
          # create user account if does not exist, set account_id in session
          if params[:email].empty? || params[:password].empty?
            flash[:error] = "Please complete email and password fields"
            redirect_to shop_checkout_path and return
          else
            @user = User.new(:email => params[:email], :password => params[:password])
            if @user.save
              session[:user_id] = @user.id
            else
              flash[:error] = "There was an error creating your account"
              redirect_to shop_checkout_path and return
            end
          end
          
        end 
          
      end

      @cart_items = ShopCartItem.where(:shop_cart_id => @shop_cart.id)

      subtotal = @cart_items.first.shop_cart.total_cart_price
      weight = @cart_items.first.shop_cart.total_cart_weight
      if subtotal > 50
        delivery = 0.00
      else
        delivery = @cart_items.first.shop_cart.delivery_charge(weight)
      end
      order_total = subtotal + delivery

      @order = ShopOrder.create(:user_id => current_user.id, :name => params[:name], :address => params[:address], :telephone => params[:telephone], :order_status_id => 1, :order_total => order_total)
      @cart_items.each do |item|
        ShopOrderItem.create(:shop_order_id => @order.id, :shop_product_id => item.shop_product.id, :quantity => item.quantity, :price => item.shop_product.sell)
      end

      ShopOrderDelivery.create(:shop_order_id => @order.id, :total_weight => weight, :price => delivery)

      # delete cart and cart_items
      @shop_cart.destroy

      # set up payment fields
      url_params = {
          :redirect_uri => confirm_shop_order_url,
          :amount => order_total,
          :name => "Little Busy Bees Shop Order ref:#{@order.id}",
          :state => @order.id,
          :user => {
            :email => current_user.email
          }
        }


      # redirect to gocardless
      url = GoCardless.new_bill_url(url_params)
      redirect_to url
    end

  end


end

app/helpers/shop_helper.rb
module ShopHelper
  
  def has_items?
    items = ShopCartItem.where("shop_cart_id = ?", session[:shop_cart_id])
  end
  
end

app/views/shop/_sidebar.html.erb
<div>
	<% unless @cart_items.empty? %>
		<div class="panel">
		<h4>Your Basket</h4>
		<ul class="basket">
		<% @cart_items.each do |itm| %>
			<li><%= itm.quantity %> x <%= itm.shop_product.name %></li>
		<% end %>
		</ul>
		<p><strong>Total: <%= number_to_currency(@cart_items.first.shop_cart.total_cart_price) %></strong> <span class="small">exc. delivery</span></p>
		<p><%= link_to "Checkout", shop_basket_path %></p>
		</div>
	<% end %>
	<h4>Shop Categories</h4>
	<% if @categories.empty? %>
		<ul>
			<li>Coming Soon</li>
		</ul>
		
	<% else %>
	<ul>
		<li><%= link_to "Shop Home", shop_path %></li>
		<% @categories.each do |cat| %>
			<li><%= link_to cat.name, shop_category_path(:name => cat.name) %></li>
		<% end %>
	</ul>
	<% end %>
</div>

app/views/shop/basket.html.erb
<div class="row mbottom30">
	<div class="three columns">
		<%= render "sidebar" %>
	</div>

	<div class="nine columns">
		<h1 class="subs">Your Basket</h1>
		<% if @cart_items.exists? %>
		<div class="row">
		<table class="nice" width="99%">
			<thead>
				<tr>
					<th>Item</th>
					<th>Item Price</th>
					<th>Quantity</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<%= form_tag shop_cart_items_update_items_path, :method => :post do |a| %>
				<% @cart_items.each_with_index do |item, i| %>
					<%= fields_for "items[]", item, :index => i do |f| %>
					<tr>
						<td><%= item.shop_product.name %></td>
						<td><%= number_to_currency(item.shop_product.sell) %></td>
						<td><%= text_field_tag "items[][quantity]", item.quantity, size: "3" %> <%= link_to "x", shop_cart_item_path(item.id), :method => :delete, confirm: "Are you sure? This will remove the item from your basket", title: "Delete?", class: "red" %> <%= hidden_field_tag "items[][id]", item.id %></td>
						<td><%= number_to_currency(item.total_price) %></td>
					</tr>
					<% end %>
				<% end %>
					<tr>
						<td></td>
						<td></td>
						<td><%= submit_tag "Update", class: "button nice radius tiny" %></td>
						<td></td>
					</tr>
				<% end %>
				<% subtotal = @cart_items.first.shop_cart.total_cart_price
				 	weight = @cart_items.first.shop_cart.total_cart_weight
					if subtotal > 50
						delivery = 0.00
					else
				 		delivery = @cart_items.first.shop_cart.delivery_charge(weight)
				 	end %>
					<tr>
						<td></td>
						<td></td>
						<td>Subtotal:</td>
						<td><%= number_to_currency(subtotal) %></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>Delivery:</td>
						<td><%= number_to_currency(delivery) %></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>Total:</td>
						<td><%= number_to_currency(subtotal + delivery) %></td>
					</tr>
			</tbody>
		</table>
		</div>
		<div class="row">
			<div class="two columns"><span class="small"><%= link_to "Empty Basket", shop_empty_basket_path, confirm: "Are you sure? This will delete all items in your basket!" %></span></div>
			<div class="four columns"></div>
			<div class="six columns"><%= link_to "<< Continue Shopping", shop_path, class: "button nice radius medium" %> or <%= link_to "Checkout", shop_checkout_path, class: "button medium nice radius green" %></div>
		</div>
		
		<% else %>
			<p>There a currently no items in your basket :(</p>
		<% end %>
	</div>
</div>




app/views/shop/category.html.erb
<div class="row mbottom30">
	<div class="three columns">
		<%= render "sidebar" %>
		<div class="home-panel mtop30">
			<h4>Monthly Craft Boxes</h4>
			<p>Have a look at our subscription packages and receive a great craft box, filled with craft projects, every month!</p>
			<p><%= link_to "Join", join_path, class: "button nice radius medium blue" %> </p>
		</div>
	</div>

	<div class="nine columns">
		<h1 class="subs"><%= params[:name] %></h1>
		<p><%= @categ.details if @categ.details %></p>

		<div class="row">
			<% if @products.empty? %>
				<p>There are no products to show in this category.</p>
			<% else %>
				<% @products.each do |prod| %>
					<div class="four columns">
						<div class="item_thumb">
							<%= link_to (image_tag prod.shop_product_images.first.image, alt: prod.name), shop_product_details_path(name: prod.name, id: prod.id) %>
							<span class="item_price"><%= number_to_currency(prod.sell) %></span>
						</div>
						<%= link_to prod.name, shop_product_details_path(name: prod.name, id: prod.id) %>
					</div>
				<% end %>
			<% end %>

		</div>

	</div>
</div>





app/views/shop/checkout.html.erb
<div class="row mbottom30">
	<div class="twelve columns">
		<h1 class="subs">Your Order</h1>
		<div class="row">
		<table class="nice" width="100%">
			<thead>
				<tr>
					<th>Item</th>
					<th>Item Price</th>
					<th>Quantity</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% @cart_items.each do |item| %>
					<tr>
						<td><%= item.shop_product.name %></td>
						<td><%= number_to_currency(item.shop_product.sell) %></td>
						<td><%= item.quantity %></td>
						<td><%= number_to_currency(item.total_price) %></td>
					</tr>
				<% end %>
				<% subtotal = @cart_items.first.shop_cart.total_cart_price
				 	weight = @cart_items.first.shop_cart.total_cart_weight
					if subtotal > 50
						delivery = 0.00
					else
				 		delivery = @cart_items.first.shop_cart.delivery_charge(weight)
				 	end %>
					<tr>
						<td></td>
						<td></td>
						<td>Subtotal:</td>
						<td><%= number_to_currency(subtotal) %></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>Delivery:</td>
						<td><%= number_to_currency(delivery) %></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td><strong>Total:</strong></td>
						<td><strong><%= number_to_currency(subtotal + delivery) %></strong></td>
					</tr>
			</tbody>
		</table>
		</div>
		<div class="row">
			<div class="two columns"><p class="small"><%= link_to "Edit Order", shop_basket_path, class: "button radius nice small" %></p></div>
			<div class="seven columns"></div>
			<div class="three columns"></div>
		</div>
		<div class="row">
			<%= form_tag shop_create_order_path, class: "nice" do |f| %>
			<div class="panel">
			<div class="six columns">
					<h4>Delivery Details</h4>
					<p class="small">* required fields</p>
					<p><%= label_tag "Name *" %>
							<%= text_field_tag :name, nil, class: "oversize input-text" %>
					</p>
					<p><%= label_tag "Address *" %>
							<%= text_area_tag :address, nil, class: "oversize input-text" %>
					</p>
					<p><%= label_tag "Telephone" %>
							<%= text_field_tag :telephone, nil, class: "oversize input-text" %>
					</p>
			</div>
			<div class="six columns">
					<h4>Account Details</h4>
					<% if current_user %>
						<p>You are signed in as <%= current_user.email %> <%= link_to "Sign Out?", logout_path %></p>
					<% else %>
					<p>If you already have an account, please enter your details below, otherwise, enter your email and choose a password to create your account.</p>
						<p><%= label_tag "Email *" %>
								<%= text_field_tag :email, nil, class: "oversize input-text" %>
						</p>
						<p>
						<%= label_tag :password, "Password *" %><%= password_field_tag :password, nil, class: "oversize input-text" %></p>
					<% end %>
			</div>
			</div>
		</div>
		<div class="row">
			<span class="right"><%= button_to "Place Order", "#", class: "button medium nice radius green" %></span>
		</div>
		<% end %>
	</div>
</div>

app/views/shop/index.html.erb
<div class="row mbottom30">
	<div class="three columns">
		<%= render "sidebar" %>
	</div>

	<div class="nine columns">
		<h1 class="subs">Shop</h1>

		<div class="row">
			<% if @products.empty? %>
				<h4>Coming Soon</h4>
				<p>Our shop will be live shortly. We will be bringing some awesome craft kits for kids of all ages, so keep checking back, or sign up for our <%= link_to "newsletter", newsletter_path %>.</p>
			<% else %>
				<% @products.each do |prod| %>
					<div class="four columns">
						<div class="item_thumb">
							<%= link_to (image_tag prod.shop_product_images.first.image.to_s, alt: prod.name), shop_product_details_path(name: prod.name, id: prod.id) %>
							<span class="item_price"><%= number_to_currency(prod.sell) %></span>
						</div>
						<%= link_to prod.name, shop_product_details_path(name: prod.name, id: prod.id) %>
					</div>
				<% end %>
			<% end %>

		</div>

	</div>
</div>

app/views/shop/product_details.html.erb
<div class="row mbottom30">
	<div class="three columns">
		<%= render "sidebar" %>
	</div>

	<div class="nine columns">
		<div class="row mbottom30">
			<div class="eight columns">
				<div id="featured">
					<% @item.shop_product_images.each do |img| %>
						<%= image_tag img.image.to_s, size: "530x530" %>
					<% end %>
				</div>
				
			</div>
			<div class="four columns">
				<h1 class="product"><%= @item.name %></h1>
				<p class="big_price"><%= number_to_currency(@item.sell) %></p>
				
				<p><%= button_to 'Add to Cart', shop_cart_items_path(:shop_product_id => @item, :quantity => 1), class: "add_to_cart" %></p>
				<hr />
				<p><%= @item.details %></p>
				<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style ">
				<a class="addthis_button_preferred_1"></a>
				<a class="addthis_button_preferred_2"></a>
				<a class="addthis_button_preferred_3"></a>
				<a class="addthis_button_preferred_4"></a>
				<a class="addthis_button_compact"></a>
				<a class="addthis_counter addthis_bubble_style"></a>
				</div>
				<script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>
				<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5074307162f9adf7"></script>
				<!-- AddThis Button END -->

			</div>
		</div>
		<div class="row mbottom30">
			<div class="twelve columns">
				<h2 class="product">Other Products in this category</h2>
				<hr />
				<% @others.each do |prod| %>
					<div class="three columns">
						<div class="item_thumb_three">
							<%= link_to image_tag(prod.shop_product_images.first.image, alt: prod.name), shop_product_details_path(name: prod.name, id: prod.id) %>
							<span class="item_price"><%= number_to_currency(prod.sell) %></span>
						</div>
						<%= link_to prod.name, shop_product_details_path(name: prod.name, id: prod.id) %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
   $(window).load(function() {
       $('#featured').orbit({
			     animation: 'fade',                  // fade, horizontal-slide, vertical-slide, horizontal-push
			     animationSpeed: 1200, 
			     pauseOnHover: true,
				 startClockOnMouseOut: true,
			     directionalNav: false,
			     fluid: true                        // or set a aspect ratio for content slides (ex: '4x3') 
			});
   });
</script>


