config/routes.rb
Bees::Application.routes.draw do

  
  

  get "comments/create"

  get "account", to: "account#index"
  get "account/subscription", to: "account#subscription"
  get "account/order", to: "account#order"

  resources :subscriptions
  post "subscriptions/new"
  get "confirm_subscription", to: "gocardless#confirm_subscription"
  get 'cancel_subscription', to: 'subscriptions#cancel_subscription'
  get 'confirm_cancel_subscription', to: 'gocardless#confirm_cancel_subscription'

  get "join", to: 'join#index' 

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  resources :sessions
  resources :users
  
  match 'articles/category', to: 'articles#category'
  match 'articles/all', to: 'articles#all'
	match 'articles/:permalink', to: 'articles#show'
	get 'blog', to: 'articles#index'
	resources :article_categories
	resources :articles
	resources :comments
  
  get 'craft_boxes', to: 'pages#craft_boxes'
  get 'about_us', to: 'pages#about_us'
	get 'terms', to: 'pages#terms'
	get 'faq', to: 'pages#faq'
  get 'privacy', to: 'pages#privacy'
  get 'contact', to: 'pages#contact'
  get 'newsletter', to: 'pages#newsletter'
  get 'reset_password', to: 'sessions#reset_password'
  get 'change_password', to: 'account#change_password'
  post 'send_contact_form', to: 'pages#send_contact_form'
  post 'newsletter_signup', to: 'pages#newsletter_signup'
  post 'send_new_password', to: 'sessions#send_new_password'
  post 'send_change_password', to: 'account#send_change_password'

  resources :shop_cart_items
  
  get 'shop', to: 'shop#index'
  match 'shop/category', to: 'shop#category'
  get 'shop/product_details'
  get 'shop/basket'
  get 'shop/checkout'
  post 'shop/create_order'
  get 'shop/empty_basket'
  post 'shop_cart_items/update_items'
  get 'confirm_shop_order', to: 'gocardless#confirm_shop_order'

  get 'manager', to: 'manager#index'
  get 'manager/subscription_details', to: 'manager#subscription_details'
  get 'manager/pack_sheets', to: 'manager#pack_sheets'
  get 'manager/orders', to: 'manager#orders'
  get 'manager/order_details', to: 'manager#order_details'
  post 'manager/update_order_status', to: 'manager#update_order_status'
  get 'manager/sort_orders', to: 'manager#sort_orders'

  get 'manager/month_end', to: 'manager#month_end'
  post 'manager/process_month_end', to: 'manager#process_month_end'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#index'

end

app/views/pages/_menu.html.erb
<ul>
	<li><%= link_to "Contact Us", contact_path %></li>
	<li><%= link_to "FAQ", faq_path %></li>
	<li><%= link_to "About Us", about_us_path %></li>
	<li><%= link_to "Terms & Conditions", terms_path %></li>
	<li><%= link_to "Privacy Policy", privacy_path %></li>
</ul>

app/views/pages/about_us.html.erb
<div class="row mbottom30">
	<div class="three columns">
		<%= render "menu" %>
	</div>
	
	<div class="nine columns">
		<h3>About Little Busy Bees</h3>
		<h5>The Story So Far</h5>
		<p>Having two children, with a few years gap in between, it became a struggle finding activities for them to do, that they would both enjoy. What I did find, no matter the age of the child, was that painting, sticking and building things was always an activity enjoyed by them both (and the adults too!)</p>
		<p>Given a project and the materials, kept them busy for hours, allowing the 'parents' to get on with jobs around the house or have a well earned cuppa and a few minutes quiet time.</p>
		<p>After looking around the craft shops, for kits and craft projects, I realised that it costs from &pound;9.99 upwards for a single kit; usually with only enough craft supplies to create one item. However, to buy the items separately, usually means buying a bulk load of paper, foam shapes, pipe cleaners etc.</p>
		<p class="left"><%= image_tag "single-box.png", width: "250" %></p>
		<p>So, I decided to bulk buy these items, package them up and give them to the children of family and friends, usually as presents. After a great response from the parents, I decided to make this into a business.</p>



		<p>I hope you and your children enjoy these craft projects as much as I do with my children.</p>
		
		<p>Best Wishes,<br />Neal</p>
		<p>Founder, Little Busy Bees</p>
	</div>
	
</div>

app/views/pages/contact.html.erb

<div class="row mbottom30">
	<div class="three columns">
		<%= render "menu" %>
	</div>
	
	<div class="six columns">
		<h3>Contact Little Busy Bees</h3>

		<p>If you have any questions, problems or suggestions, please use the form below to contact us and we will reply back as soon as we can.</p>
		<p>Alternatively, you can phone on <strong>0161 408 3334</strong> or email <strong>contact@littlebusybees.co.uk</strong></p>
		
		<%= form_tag(send_contact_form_path, :method => 'post', class: "nice") do %>
		    <p>
		      <%= label_tag :name %>
		      <%= text_field_tag "name", @name, class: "input-text" %>
		    </p>

		    <p>
		      <%= label_tag :email %>
		      <%= text_field_tag "email", @email, class: "input-text" %>
		    </p>

		    <p>
		      <%= label_tag "Message" %>
		      <%= text_area_tag "message", @message, class: "input-text", rows: 15 %>
		    </p>

		  <p>
		    <%= submit_tag "Send", class: "nice button radius small green" %>
		  </p>
		<% end %>
		
		
	</div>

	<div class="three columns">
		<h4>Company Stuff</h4>
		<p>Little Busy Bees is operated under Little Busy Box Company Ltd, who are registered in England. Reg. number 8179263.</p>
	</div>
	
</div>

app/views/pages/craft_boxes.html.erb
<div class="row mbottom30">
	
	<div class="eight columns">
		<h3>Craft Boxes</h3>
		<p>Our craft boxes are aimed at children from 3 years up to 7 years, although older children (and adults) enjoy using them too.</p>
		<div id="featured">
			<%= image_tag "box-home.jpg" %>
			<%= image_tag "pirate-box-josh1.jpg" %>
			<%= image_tag "single-box-slide.jpg" %>
			<%= image_tag "pirate-box-josh2.jpg" %>
		</div>
		<p></p>
		<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style ">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_pinterest_pinit"></a>
				<a class="addthis_counter addthis_pill_style"></a>
				</div>
				<script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>
				<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5074307162f9adf7"></script>
				<!-- AddThis Button END -->
		<p>Each craft box comes with, at least, 3 projects to complete and includes plenty of materials to keep the children busy for hours.</p>

	</div>
	
	<div class="four columns">
		<div class="panel-emph">
			<h4>Join Today</h4>
			<p>Have a look at our subscription packages and receive a great craft box, filled with craft projects, every month!</p>
			<p><%= link_to "Join", join_path, class: "button nice radius medium blue" %> </p>
		</div>
	</div>
	
</div>

<script type="text/javascript">
   $(window).load(function() {
       $('#featured').orbit({
			     animation: 'fade',                  // fade, horizontal-slide, vertical-slide, horizontal-push
			     animationSpeed: 1200, 
			     pauseOnHover: true,
					 startClockOnMouseOut: true,
			     directionalNav: false,
			     fluid: true                         // or set a aspect ratio for content slides (ex: '4x3') 
			});
   });
</script>

app/views/pages/faq.html.erb
<div class="row mbottom30">
	<div class="three columns">
		<%= render "menu" %>
	</div>
	
	<div class="five columns">
		<h4>Frequently Asked Questions</h4>
		
		<dl class="nice vertical tabs">
  		<dd><a href="#whatsitabout">So, what's it all about?</a></dd>
  		<dd><a href="#howdoijoin">How do I join?</a></dd>
  		<dd><a href="#paymentoptions">What are the payment options?</a></dd>
  		<dd><a href="#whatsinthebox">What's included in the boxes?</a></dd>
  		<dd><a href="#whenwillitarrive">When will it arrive?</a></dd>
  		<dd><a href="#wheredeliver">Where do you deliver to?</a></dd>
  		<dd><a href="#changeaddress">Can I change my delivery address?</a></dd>
  		<dd><a href="#boxnotarrived">My box hasn't arrived. Help!</a></dd>
  		<dd><a href="#whengetcharged">When do I get charged?</a></dd>
  		<dd><a href="#sendagift">Can I send it as a gift?</a></dd>
  		<dd><a href="#damages">What about damaged items?</a></dd>
  		<dd><a href="#cancellation">What's your cancellation policy?</a></dd>
		</dl>
		
		
	</div>
	
	<div class="four columns">
		<div class="panel">
			<h3>Answer</h3>
		<ul class="tabs-content">
  		<li id="whatsitaboutTab"><p>Little Busy Bees is a monthly subscription service for children's craft projects.</p>
  			<p>Each month you will receive a box, packed with great projects, based around a theme; such as Pirates or Jungle animals.</p>
  			<p>Our aim is to create an enjoyable, educational and fun (and sometimes messy!) experience for the children. Plus, the grown ups get to have a break too.</p></li>
  		<li id="howdoijoinTab"><p>Joining is simple. Select your <%= link_to "kids craft subscription package here, ", join_path %> enter the child's details, delivery details and payment details.</p> <p>That's it!</p></li>
  		<li id="paymentoptionsTab"><p>We currently use a company called GoCardless to process our payments.</p><p>The difference between these and the likes of Paypal et al is that you subscribe using a direct debit system (with your bank details) and not your credit or debit cards.</p><p>It's also a lot cheaper, for us, to process your payments, meaning we can pass the savings onto you directly.</p><p>They are also a great bunch of people! You can find more info about them at <%= link_to "GoCardless", "http://gocardless.com/about", :target => "_blank" %>.</p></li>
  		<li id="whatsintheboxTab"><p>Within each craft box, you will find all* the items needed to complete the projects. This includes paints, glue, colours, paper, paint brushes, instructions etc. We even include a disposable apron, to keep the little ones a bit cleaner.</p><p>* Some items we can not include, for obvious reasons; such as warm water, however, our instructions will tell you the items you may also require to complete the project. These should be readily available in most homes (scissors, for example).</p></li>
  		<li id="whenwillitarriveTab"><p>Our delivery process is based around the 15th of each month. Depending on the weight of the craft boxes, will depend on which delivery company we use. However, you should receive your delivery between 3 and 7 days after this date.</p></li>
  		<li id="wheredeliverTab"><p>Currently, we only deliver our craft boxes to Mainland UK. However, we are looking to expand this option, so please keep your ears peeled.</p></li>
  		<li id="changeaddressTab"><p>Yes you certainly can. Just sign into your account, select your subscription package and edit the delivery address details. It would be advisable to try and change your details, either, before the 10th of the month or after the 20th. Just so we don't end up sending your boxes to the wrong place when we are processing our deliveries.</p></li>
  		<li id="boxnotarrivedTab"><p>Our craft boxes are shipped between the 15th and 18th of every month and should only take a few days to arrive.</p><p>If you have still not received your box by the 25th of the month, please let us know and we will chase it up for you.</p></li>
  		<li id="whengetchargedTab"><p>Our charging process takes place around the 14th of every month. If you have signed up before this date, you will be charged in the current month.</p><p>If you sign up after the 14th, your first payment and delivery will take place the following month. You will be notified each time a payment has successfully been made.</p></li>
  		<li id="sendagiftTab"><p>If you're feeling generous, then you can send the craft boxes as a gift. Simply choose the gift option, from the main menu, select the subscription package you require and enter your details. You can also add a special message, which we will put into the boxes for you.</p><p>Gift subscriptions are paid for in full at the time of ordering, they are not a monthly payment.</p></li>
  		<li id="damagesTab"><p>Although we carefully check and package each of our craft boxes, with the nature of the delivery system, there may be the odd damaged item on arrival. We don't like this, but once it has left our building, your craft box is in the hands of the courier.</p><p>Should you find that any items are damaged, please contact us straight away and we will send out a replacement item.</p></li>
  		<li id="cancellationTab"><p>Obviously you're not going to want to cancel because our craft boxes are so awesome!</p><p>However, should you have to, because your children have actually moved out now and you have a massive pile of craft boxes sat in your living room. We have made it very easy for you to do so.</p><p>Simply sign into your account, select the subscription package and hit the cancel button. You will be asked to make sure, just in case you have got fat fingers and hit the wrong button, then upon clicking OK your subscription will be cancelled.</p><p>We will shed a tear and mourn the loss of a great customer, but carry on making awesome craft boxes for other children. Just not yours anymore.</p>
  			<p>If you have opted for the 3 or 6 monthly subscription packages, unfortunately we do not provide refunds for outstanding boxes. However, you will still receive any boxes, up until the end of your subscription period.</p></li>
		</ul>
		<p>&nbsp;</p>
		</div>
	</div>
	
</div>

app/views/pages/index.html.erb
<div class="row mbottom30">
	<!-- >
	<div class="four columns">
		<h1 class="home-title">Kids Craft Boxes</h1>
		<h2 class="home-title">Receive a craft box, every month, packed with projects for your children.</h2>
		<ul>
			<li>Free Delivery</li>
			<li>For children aged 3 to 7 (and up)</li>
			<li>All craft materials included</li>
			<li>From <strong>&pound;14.99</strong> per month</li>
		</ul>
		<p><%= link_to "Join Today", join_path, class: "button nice radius blue large" %></p>
	</div>
	
	<div class="eight columns">
		<%= image_tag "box-home.jpg", class: "home-image" %>
	</div>
	<-->
	<div class="twelve columns">
		<div id="featured">
			<%= image_tag "home-slide-1.jpg", class: "home-image" %>
			<%= image_tag "home-slide-2.jpg", class: "home-image" %>
			<%= image_tag "home-slide-3.jpg", class: "home-image" %>
		</div>
		<div class="home-overlay four">
			<h1 class="home-title">Kids Craft Boxes</h1>
			<h2 class="home-title">Receive a craft box, every month, packed with projects for your children.</h2>
			<ul>
				<li>Free Delivery</li>
				<li>For children aged 3 to 7 (and up)</li>
				<li>All craft materials included</li>
				<li>From <strong>&pound;14.99</strong> per month</li>
			</ul>
			<p><%= link_to "Join Today", join_path, class: "button nice radius blue large" %></p>
		</div>
	</div>
</div>

<div class="row mbottom30">
	<div class="four columns">
		<div class="home-panel how">
			<h5>How It Works</h5>
			<ul>
				<li>1. Choose plan</li>
				<li>2. Receive craft box <span class="small">(with free delivery)</span></li>
				<li>3. Get creative</li>
				<li><%= link_to "Join Today", join_path, class: "button nice small radius orange" %>
			</ul>
		</div>
	</div>
	
	<div class="four columns">
		<div class="home-panel box">
			<h5>In The Box</h5>
			<p>Each box contains all the craft materials to complete the projects. Just add creativity.</p>
			<p>With, at least, 3 projects in every box, we provide the fun for hours.</p>
		</div>
	</div>
	
	<div class="four columns last-column">
		<div class="home-panel sibling">
			<h5>Sibling Option</h5>
			<p>Our craft box subscription plans come with a sibling option, adding extra craft products into the box so each child gets their own craft materials.<br />
				So, no more arguing over the paints.</p>
		</div>
	</div>
</div>

<script type="text/javascript">
   $(window).load(function() {
       $('#featured').orbit({
			     animation: 'fade',                  // fade, horizontal-slide, vertical-slide, horizontal-push
			     animationSpeed: 1800,
			 		 advanceSpeed: 6000,
			     pauseOnHover: true,
					 startClockOnMouseOut: true,
			     directionalNav: false,
			     fluid: true                         // or set a aspect ratio for content slides (ex: '4x3') 
			});
   });
</script>

app/views/pages/newsletter.html.erb
<div class="row mbottom30">

	<h2>Sign Up to Our Newsletter</h2>
	
	<p>If you would like to receive updates containing information about Little Busy Bees, our competitions, new craft ideas and special offers, please enter your email address below.</p>

	<%= form_tag newsletter_signup_path, class: "nice" do %>
		<p><%= text_field_tag 'email', nil, class: "input-text", :placeholder => 'Your email address' %></p>
		<p><%= submit_tag "Subscribe", class: "nice button radius small red" %></p>
	<% end %>

	<p>We will not send you any spam mail, nor sell or give your details away to any other third parties. It's just us and you baby! And if you do get fed up of us rambling on, you can easily un-subscribe by clicking on the un-subscribe links in any of the emails we send you.</p>

</div>

app/views/pages/privacy.html.erb

<div class="row mbottom30">
	<div class="three columns">
		<%= render "menu" %>
	</div>
	
	<div class="nine columns">
		<h3>Privacy Policy</h3>
		
		<p>Little Busy Box Company Ltd ("We") are committed to protecting and respecting your privacy.</p>
		<p>This policy (together with our <%= link_to "terms of use", terms_path %> and any other documents referred to on it) sets out the basis on which any personal data we collect from you, or that you provide to us, will be processed by us.  Please read the following carefully to understand our views and practices regarding your personal data and how we will treat it. We keep certain basic information when you visit our website and recognise the importance of keeping that information secure and letting you know what we will do with it.</p>
		<!-- <p>For the purpose of the Data Protection Act 1998 (the Act), the data controller is [COMPANY NAME] of [ADDRESS] (registration number [REG NO.]). </p> -->
		<p>This policy only applies to our site. If you leave our site via a link or otherwise, you will be subject to the policy of that website provider. We have no control over that policy or the terms of the website and you should check their policy before continuing to access the site.</p>
	
		<h4>Information We May Collect From You</h4>
	
		<p>We may collect and process the following data about you:</p>
		<ul>
			<li>Information that you provide by filling in forms on www.littlebusybees.co.uk (our site). This includes information provided at the time of registering to use our site, subscribing to our service or requesting further services. We may also ask you for information when you report a problem with our site.</li>
			<li>If you contact us, we may keep a record of that correspondence.</li>
			<li>We may also ask you to complete surveys that we use for research purposes, although you do not have to respond to them.</li>
			<li>Details of your visits to our site including, but not limited to, traffic data, location data, weblogs, operating system, browser usage and other communication data, whether this is required for our own billing purposes or otherwise and the resources that you access. </li>
		</ul>

		<h4>Ip Addresses And Cookies</h4>
		<p>We may collect information about your computer, including where available your IP address, operating system and browser type, for system administration and to report aggregate information to our advertisers. This is statistical data about our users' browsing actions and patterns, and does not identify any individual and we will not collect personal information in this way.</p>
		<p>We may obtain information about your general internet usage by using a cookie file which is stored on the hard drive of your computer. Cookies contain information that is transferred to your computer's hard drive. They help us to improve our site and to deliver a better and more personalised service. They enable us:</p>
		<ul>
			<li>To estimate our audience size and usage pattern.</li>
			<li>To store information about your preferences, and so allow us to customise our site according to your individual interests.</li>
			<li>To speed up your searches.</li>
			<li>To recognise you when you return to our site. </li>
		</ul>
		<p>You may refuse to accept cookies by activating the setting on your browser which allows you to refuse the setting of cookies. However, if you select this setting you may be unable to access certain parts of our site. Unless you have adjusted your browser setting so that it will refuse cookies, our system will issue cookies when you log on to our site.</p>
		
		<h4>Where We Store Your Personal Data</h4>

		<p>The data that we collect from you may be transferred to, and stored at, a destination outside the European Economic Area ("EEA"). It may also be processed by staff operating outside the EEA who work for us or for one of our suppliers. Such staff maybe engaged in, among other things, the fulfilment of your order, the processing of your payment details and the provision of support services. By submitting your personal data, you agree to this transfer, storing or processing. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy.</p>
		<p>All information you provide to us is stored on our secure servers. Any payment transactions will be encrypted. Where we have given you (or where you have chosen) a password which enables you to access certain parts of our site, you are responsible for keeping this password confidential. We ask you not to share a password with anyone.</p>
		<p>Unfortunately, the transmission of information via the internet is not completely secure. Although we will do our best to protect your personal data, we cannot guarantee the security of your data transmitted to our site; any transmission is at your own risk. Once we have received your information, we will use strict procedures and security features to try to prevent unauthorised access.</p>
		
		<h4>Uses Made Of The Information</h4>

		<p>We use information held about you in the following ways:</p>
		<ul>
			<li>To ensure that content from our site is presented in the most effective manner for you and for your computer. </li>
			<li>To provide you with information, products or services that you request from us or which we feel may interest you, where you have consented to be contacted for such purposes. </li>
			<li>To carry out our obligations arising from any contracts entered into between you and us.</li>
			<li>To allow you to participate in interactive features of our service, when you choose to do so.</li>
			<li>To notify you about changes to our service.</li>
		</ul>
		<p>We will not sell or forward your details to any third party, unless it is required by law.</p>
		
		<h4>Disclosure Of Your Information</h4>

		<p>We may disclose your personal information to third parties:</p>
		<ul>
			<li>In the event that we sell or buy any business or assets, in which case we may disclose your personal data to the prospective seller or buyer of such business or assets.</li>
			<li>If we are under a duty to disclose or share your personal data in order to comply with any legal obligation, our customers, or others. This includes exchanging information with other companies and organisations for the purposes of fraud protection and credit risk reduction.</li>
		</ul>

		<h4>Your Rights</h4>

		<p>You have the right to ask us not to process your personal data for marketing purposes. We will usually inform you (before collecting your data) if we intend to use your data for such purposes or if we intend to disclose your information to any third party for such purposes. You can exercise your right to prevent such processing by checking certain boxes on the forms we use to collect your data.  You can also exercise the right at any time by contacting us at contact@littlebusybees.co.uk.</p>
		<p>Our site may, from time to time, contain links to and from the websites of our partner networks, advertisers and affiliates.  If you follow a link to any of these websites, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for these policies.</p>  <p>Please check these policies before you submit any personal data to these websites.</p>

		<h4>Access To Information</h4>

		<p>The Act gives you the right to access information held about you. Your right of access can be exercised in accordance with the Act. Any access request may be subject to a fee of £10 to meet our costs in providing you with details of the information we hold about you.</p>

		<h4>Changes To Our Privacy Policy</h4>

		<p>Any changes we may make to our privacy policy in the future will be posted on this page and, where appropriate, notified to you by e-mail. However, we advise that you check this page regularly to keep up to date with any necessary changes.</p>

		<h4>Contact</h4>

		<p>Questions, comments and requests regarding this privacy policy are welcomed and should be addressed to contact@littlebusybees.co.uk.</p>

		
	</div>
	
	
</div>