config/routes.rb
Bees::Application.routes.draw do

  
  

  get "comments/create"

  get "account", to: "account#index"
  get "account/subscription", to: "account#subscription"
  get "account/order", to: "account#order"

  resources :subscriptions
  post "subscriptions/new"
  get "confirm_subscription", to: "gocardless#confirm_subscription"
  get 'cancel_subscription', to: 'subscriptions#cancel_subscription'
  get 'confirm_cancel_subscription', to: 'gocardless#confirm_cancel_subscription'

  get "join", to: 'join#index' 

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  resources :sessions
  resources :users
  
  match 'articles/category', to: 'articles#category'
  match 'articles/all', to: 'articles#all'
	match 'articles/:permalink', to: 'articles#show'
	get 'blog', to: 'articles#index'
	resources :article_categories
	resources :articles
	resources :comments
  
  get 'craft_boxes', to: 'pages#craft_boxes'
  get 'about_us', to: 'pages#about_us'
	get 'terms', to: 'pages#terms'
	get 'faq', to: 'pages#faq'
  get 'privacy', to: 'pages#privacy'
  get 'contact', to: 'pages#contact'
  get 'newsletter', to: 'pages#newsletter'
  get 'reset_password', to: 'sessions#reset_password'
  get 'change_password', to: 'account#change_password'
  post 'send_contact_form', to: 'pages#send_contact_form'
  post 'newsletter_signup', to: 'pages#newsletter_signup'
  post 'send_new_password', to: 'sessions#send_new_password'
  post 'send_change_password', to: 'account#send_change_password'

  resources :shop_cart_items
  
  get 'shop', to: 'shop#index'
  match 'shop/category', to: 'shop#category'
  get 'shop/product_details'
  get 'shop/basket'
  get 'shop/checkout'
  post 'shop/create_order'
  get 'shop/empty_basket'
  post 'shop_cart_items/update_items'
  get 'confirm_shop_order', to: 'gocardless#confirm_shop_order'

  get 'manager', to: 'manager#index'
  get 'manager/subscription_details', to: 'manager#subscription_details'
  get 'manager/pack_sheets', to: 'manager#pack_sheets'
  get 'manager/orders', to: 'manager#orders'
  get 'manager/order_details', to: 'manager#order_details'
  post 'manager/update_order_status', to: 'manager#update_order_status'
  get 'manager/sort_orders', to: 'manager#sort_orders'

  get 'manager/month_end', to: 'manager#month_end'
  post 'manager/process_month_end', to: 'manager#process_month_end'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="<%= @meta_desc %>" />
	<meta name="keywords" content="<%= @meta_keys %>" />
	<link href="favicon.jpg" rel="icon" type="image/jpg" />
	
	<title><%= page_title %></title>
  
	<!-- Included CSS Files -->
	<link href='http://fonts.googleapis.com/css?family=Pontano+Sans' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
  <script type="text/javascript" charset="utf-8">
	//if (jQuery.cookie('cc_cookie_accept') == "cc_cookie_accept") {
		$(document).ready(function () {
		$.cookieCuttr();	
		});
	  </script>
	  <!-- Google Stuff -->
	  <script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-31256435-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	//} 
</script>
</head>
<body>
	<div id="main-container">
	<div id="top-login">
		<div class="row">
			<div class="four columns">
				<%= link_to (image_tag "social/facebook.png"), "http://www.facebook.com/littlebusybees", alt: "Facebook", title: "Facebook" %> <%= link_to (image_tag "social/twitter.png"), "http://www.twitter.com/littlebusybees/", alt: "Twitter", title: "Twitter" %> <%= link_to (image_tag "social/pinterest.png"), "http://www.pinterest.com/littlebusybees/", alt: "Pinterest", title: "Pinterest" %>
			</div>
			
			<div class="eight columns">
				<div class="right">
				<% if current_basket && current_basket.shop_cart_items.count > 0 %>
					<%= link_to "Basket (#{pluralize(current_basket.total_cart_quantity, "item")})", shop_basket_path %> | 
				<% end %>
				<% if current_user %>
				Hi <%= current_user.email %>. <%= link_to "My Account", account_path %> | <%= link_to "Log Out", logout_path %>
			<% else %>
		 		<%= link_to "Login", login_path %> | <%= link_to "Signup", signup_path %>
			<% end  %>
				</div>
			</div>
			
			
		</div>
	</div>
	<div id="top-nav">
		
		<div class="row">
			<div class="four columns">
				<%= link_to (image_tag "logo-sketched.png"), root_url, alt: "Little Busy Bees", title: "Little Busy Bees Craft Boxes" %>
			</div>
			<div class="eight columns">
				<ul class="nav-bar">
					<li><%= link_to "Home", root_path, class: "main" %></li>
					<li><%= link_to "Join", join_path, class: "main" %></li>
					<li><%= link_to "Craft Boxes", craft_boxes_path, class: "main" %></li>
					<li><%= link_to "Shop", shop_path, class: "main new" %></li>
					<li><%= link_to "Blog", articles_path, class: "main" %></li>
					<li><%= link_to "Contact", contact_path, class: "main" %></li>
				</ul>
			</div>
		</div>
	</div>
	
	<% if admin_user_signed_in? %>
	<div class="row hide-on-print">
		<div class="twelve columns">
			<ul class="nav-bar">
				<li><%= link_to "Admin Home", manager_path, class: "main" %></li>	
				<li><%= link_to "Pack Sheets", manager_pack_sheets_path, class: "main", target: "_blank" %></li>
				<li><%= link_to "Orders", manager_orders_path, class: "main" %></li>
				<li><%= link_to "Log Out", destroy_admin_user_session_path, class: "main" %></li>
			</ul>
		</div>
	</div>
	<% end %>

  <div class="container">
    <div class="container">
			
		<div class="row">
			<% if flash[:error] %>
				<div class="alert-box error">
					<%= flash[:error] %>
					<a href="" class="close">&times;</a>
				</div>
			<% end %>

			<% if flash[:notice] %>
				<div class="alert-box success fade">
					<%= flash[:notice] %>
					<a href="" class="close">&times;</a>
				</div>
			<% end %>

			<% if flash[:alert] %>
				<div class="alert-box error fade">
					<%= flash[:alert] %>
					<a href="" class="close">&times;</a>
				</div>
			<% end %>
		</div>

			<%= yield %>
	</div>

		

	</div>
	<div id="newsletter-bar">
		<div class="row">
			<div class="four columns">
				<h5>Newsletter Signup</h5>
				<p>Enter your email address to receive our latest news, reviews and competitions.</p>
			</div>
			<div class="four columns">
				<%= form_tag newsletter_signup_path, class: "nice" do %>
					<%= text_field_tag 'email', nil, class: "input-text", :placeholder => 'Your email address' %>
			</div>
			<div class="four columns">
					<%= submit_tag "Signup", class: "button large nice radius black" %>
				<% end %>
			</div>
		</div>
	</div>

	<div id="footer">
			<div class="row">
				<div class="twelve columns">
						
						<div class="eight columns">
							<h5>Latest Blog Posts</h5>
							<ul>
								<% latest_blog_posts.each do |blog| %>
									<li><%= link_to blog.title, article_path(blog.permalink) %></li>
								<% end %>
							</ul>
						</div>
						<div class="four columns">
								<h5>Pages</h5>
								<ul>
									<li><%= link_to "shop", shop_path %></li>
									<li><%= link_to "contact", contact_path %></li>
									<li><%= link_to "faq", faq_path %></li>
									<li><%= link_to "about us", about_us_url %></li>
									<li><%= link_to "terms", terms_path %></li>
								</ul>
						</div>
				</div>
			</div>
			<div class="row mtop20">
				<div class="four columns">
				</div>
				<div class="four columns">
					<p class="small">&copy; Copyright 2012 Little Busy Box Company Ltd</p>
				</div>
				<div class="four columns">
					<p><%= image_tag "busy-box-300x100.png", :width => "150", alt: "Little Busy Box Company", title: "Little Busy Box Company" %></p>
				</div>
			</div>
		</div>
	</div>
</body>
</html>